apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: my-mew-app-devfile-sample-ymzw-sample
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: my-mew-app-devfile-sample-ymzw-sample
    app.kubernetes.io/part-of: my-mew-app
  name: my-mew-app-devfile-sample-ymzw-sample
  namespace: alexeykazakov
spec:
  ports:
  - port: 3001
    targetPort: 3001
  selector:
    app.kubernetes.io/instance: my-mew-app-devfile-sample-ymzw-sample
status:
  loadBalancer: {}
